### ISSUE TITLE
Roadmap Link

### ISSUE THREAD

**Issue by Snowleppy** [Snowleppy/Snowleppy#2]
Link for our roadmap that outlines the milestones we plan to achieve.

![image](https://github.com/Snowleppy/Snowleppy/assets/157665928/61f6683f-cabc-409c-a31a-6734bede5d77)

**Comment by PythonForForex** [comment]
Great idea about the roadmap! I'm all in for getting those milestones we've been talking about on Basecamp laid out clearly for everyone to see. 

Let's set up a new repo where we can pull all that info together. We can collaborate on this and make the repo public once ready
